"""SQLAlchemy 2.0 models for the Library layer (DD §10 "-- Library" block).

Must match `migrations/versions/0005_library.py` exactly — hand-written, not
autogenerated, kept in sync by hand (see tests/unit/test_models_match_migration.py).

Shares `Base` with app/domain/models_jb2.py so both modules' tables live in
one MetaData — the migration/model comparison test walks a single registry.

See DD §5 (core domain model / substep types), §7 (instruction library
builder / versioning rules), and the docstring of migration 0005 for the
uniqueness deviations (instruction_sets, failure_codes) from the DD's
literal §10 schema sketch.
"""
from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    JSON,
    Boolean,
    CheckConstraint,
    ForeignKey,
    Integer,
    Text,
    UniqueConstraint,
    Uuid,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func

from app.domain.models_jb2 import Base, _uuid_pk

# ponytail: same portable JSON type as models_jb2.py -- real JSONB on
# Postgres via the variant, plain JSON text on SQLite for in-process tests.
_JSONB = JSON().with_variant(JSONB(), "postgresql")


class Product(Base):
    __tablename__ = "products"

    id: Mapped[uuid.UUID] = _uuid_pk()
    name: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    variant_schema: Mapped[dict | None] = mapped_column(_JSONB, nullable=True)
    active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="true")


class ProductPartMap(Base):
    __tablename__ = "product_part_map"

    id: Mapped[uuid.UUID] = _uuid_pk()
    product_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("products.id"), nullable=False, index=True
    )
    jb2_part_number: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    variant_values: Mapped[dict | None] = mapped_column(_JSONB, nullable=True)


class InstructionSet(Base):
    """DD §7.1: library entry for one operation type on one product,
    versioned; `product_id` null = global scope.

    DEVIATION from DD §10 literal text: uniqueness is enforced as
    (product_id, title, version), not (product_id, operation_match,
    version) — `operation_match` is jsonb and can't portably sit in a
    unique constraint. See migrations/versions/0005_library.py docstring.
    """

    __tablename__ = "instruction_sets"
    __table_args__ = (
        CheckConstraint(
            "state in ('draft','in_review','published','retired')",
            name="ck_instruction_sets_state",
        ),
        UniqueConstraint(
            "product_id", "title", "version", name="uq_instruction_sets_product_title_version"
        ),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    product_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("products.id"), nullable=True, index=True
    )
    operation_match: Mapped[dict] = mapped_column(_JSONB, nullable=False)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    state: Mapped[str] = mapped_column(Text, nullable=False, server_default="draft")
    version: Mapped[int] = mapped_column(Integer, nullable=False, server_default="1")
    parent_version_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("instruction_sets.id"), nullable=True, index=True
    )
    est_minutes: Mapped[int | None] = mapped_column(Integer, nullable=True)
    # ponytail: plain text, no FK -- operators table arrives Phase 3.
    created_by: Mapped[str | None] = mapped_column(Text, nullable=True)
    published_by: Mapped[str | None] = mapped_column(Text, nullable=True)
    published_at: Mapped[datetime | None] = mapped_column(nullable=True)
    created_at: Mapped[datetime] = mapped_column(nullable=False, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(nullable=False, server_default=func.now())


class Step(Base):
    __tablename__ = "steps"
    __table_args__ = (
        UniqueConstraint("instruction_set_id", "seq", name="uq_steps_instruction_set_seq"),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    instruction_set_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("instruction_sets.id"), nullable=False, index=True
    )
    seq: Mapped[int] = mapped_column(Integer, nullable=False)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    body_html: Mapped[str | None] = mapped_column(Text, nullable=True)
    est_minutes: Mapped[int | None] = mapped_column(Integer, nullable=True)


class Substep(Base):
    """DD §5 substep types: action, measurement, inspection, photo,
    material, signoff."""

    __tablename__ = "substeps"
    __table_args__ = (
        CheckConstraint(
            "type in ('action','measurement','inspection','photo','material','signoff')",
            name="ck_substeps_type",
        ),
        UniqueConstraint("step_id", "seq", name="uq_substeps_step_seq"),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    step_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("steps.id"), nullable=False, index=True
    )
    seq: Mapped[int] = mapped_column(Integer, nullable=False)
    type: Mapped[str] = mapped_column(Text, nullable=False)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    body_html: Mapped[str | None] = mapped_column(Text, nullable=True)
    required: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="true")
    condition: Mapped[dict | None] = mapped_column(_JSONB, nullable=True)
    measurement_spec: Mapped[dict | None] = mapped_column(_JSONB, nullable=True)
    media: Mapped[dict] = mapped_column(_JSONB, nullable=False, server_default="[]")
    signoff_role: Mapped[str | None] = mapped_column(Text, nullable=True)


class FailureCode(Base):
    """DD §9.6 / §7.2: failure-code taxonomy, per product and global
    (`product_id` null). Global-scope uniqueness on `code` alone is
    enforced by a Postgres partial unique index created in migration 0005
    (not representable as a portable SQLAlchemy Column/model construct);
    see that migration's docstring.
    """

    __tablename__ = "failure_codes"
    __table_args__ = (
        UniqueConstraint("product_id", "code", name="uq_failure_codes_product_code"),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    product_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("products.id"), nullable=True, index=True
    )
    code: Mapped[str] = mapped_column(Text, nullable=False)
    label: Mapped[str] = mapped_column(Text, nullable=False)
    category: Mapped[str | None] = mapped_column(Text, nullable=True)
    jb2_reason_number: Mapped[int | None] = mapped_column(Integer, nullable=True)
    active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="true")
