"""SQLAlchemy 2.0 models for the Execution layer (DD §10 "-- Execution" block,
the `work_orders`/`units`/`plan_operations`/`plan_pdfs` subset — the rest of
that block, e.g. `build_boxes`/`work_sessions`, is Phase 3).

Must match `migrations/versions/0006_execution_core.py` exactly — hand-written,
not autogenerated, kept in sync by hand (see
tests/unit/test_models_match_migration.py).

Shares `Base` with app/domain/models_jb2.py and models_library.py so all
three modules' tables live in one MetaData.

See DD §5 (WorkOrder/Unit/ExecutionPlan), §4.3 (order ingestion rules), §6.1/
6.2 (order arrival / route population), §17.4/17.5 (qty/routing-drift
reconciliation).

DEVIATIONS from the DD §10 literal schema sketch, both scoped out because
their FK targets don't exist yet (stations/build_boxes are Phase 3 tables):
  - `plan_operations.station_hint` (DD: `fk null`) is omitted entirely.
  - `units.current_plan_op_id` has no counterpart column omission, but its FK
    is only addable *after* `plan_operations` is created in the same
    migration (see migration docstring) -- the model declares it directly
    since SQLAlchemy resolves string FK targets lazily against the shared
    MetaData, so declaration order here doesn't need to mirror the
    migration's two-phase (ALTER TABLE) approach.
"""
from __future__ import annotations

import uuid
from datetime import date, datetime

from sqlalchemy import (
    JSON,
    Boolean,
    CheckConstraint,
    Date,
    ForeignKey,
    Integer,
    Text,
    UniqueConstraint,
    Uuid,
    false,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func

from app.domain.models_jb2 import Base, _uuid_pk

# ponytail: same portable JSON type as models_jb2.py/models_library.py.
_JSONB = JSON().with_variant(JSONB(), "postgresql")

WORK_ORDER_STATUSES = (
    "pending_sync",
    "ready",
    "in_progress",
    "completed",
    "blocked_no_instructions",
    "cancelled",
    "cancel_requested",
    "routing_drift",
)

PLAN_OPERATION_STATUSES = ("pending", "active", "done", "skipped")


class WorkOrder(Base):
    """DD §5: MES execution record for one JB2 order line item."""

    __tablename__ = "work_orders"
    __table_args__ = (
        CheckConstraint(
            "status in ('pending_sync','ready','in_progress','completed',"
            "'blocked_no_instructions','cancelled','cancel_requested','routing_drift')",
            name="ck_work_orders_status",
        ),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    jb2_line_item_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("jb2_order_line_items.id"),
        nullable=False,
        unique=True,
    )
    # ponytail: not-null -- a work order is only ever created once the line
    # item's part number resolves to a product (see
    # app/domain/workorders.create_from_line_item); an unmapped part yields a
    # mapping_exceptions row and no WorkOrder at all, so there's no
    # in-between state where a WO exists without a product.
    product_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("products.id"), nullable=False, index=True
    )
    variant_values: Mapped[dict | None] = mapped_column(_JSONB, nullable=True)
    qty: Mapped[int] = mapped_column(Integer, nullable=False)
    due_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default="pending_sync")
    plan_version: Mapped[int] = mapped_column(Integer, nullable=False, server_default="1")
    priority: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(nullable=False, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(nullable=False, server_default=func.now())


class Unit(Base):
    """DD §5: one physical serialized item within a WorkOrder. CR-007: the
    serial pre-exists in Atlas's system and is entered at kit-up (Phase 3) --
    `serial_number` is null at creation."""

    __tablename__ = "units"
    __table_args__ = (
        UniqueConstraint("work_order_id", "unit_no", name="uq_units_work_order_unit_no"),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    work_order_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("work_orders.id"), nullable=False, index=True
    )
    unit_no: Mapped[int] = mapped_column(Integer, nullable=False)
    # Uniqueness "when set" is a Postgres partial unique index added by the
    # migration (mirrors the failure_codes global-scope pattern in
    # migrations/versions/0005_library.py) -- not portably expressible as a
    # SQLAlchemy column-level constraint, so it isn't declared here.
    serial_number: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default="queued")
    first_pass: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="true")
    rework_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    remake_of_unit_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("units.id"), nullable=True
    )
    current_plan_op_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("plan_operations.id"), nullable=True
    )
    completed_at: Mapped[datetime | None] = mapped_column(nullable=True)


class PlanOperation(Base):
    """DD §5/§8: one frozen operation in a WorkOrder's ExecutionPlan -- one
    row per JB2 routing step, `frozen_content` is a full deep copy of the
    bound InstructionSet's steps+substeps at release time (the freeze;
    never a reference back to the live library rows)."""

    __tablename__ = "plan_operations"
    __table_args__ = (
        CheckConstraint(
            "status in ('pending','active','done','skipped')",
            name="ck_plan_operations_status",
        ),
        UniqueConstraint("work_order_id", "seq", name="uq_plan_operations_work_order_seq"),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    work_order_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("work_orders.id"), nullable=False, index=True
    )
    seq: Mapped[int] = mapped_column(Integer, nullable=False)
    jb2_routing_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("jb2_order_routings.id"), nullable=True
    )
    operation_code: Mapped[str | None] = mapped_column(Text, nullable=True)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    instruction_set_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("instruction_sets.id"), nullable=True
    )
    instruction_version: Mapped[int | None] = mapped_column(Integer, nullable=True)
    frozen_content: Mapped[dict] = mapped_column(_JSONB, nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default="pending")
    est_minutes: Mapped[int | None] = mapped_column(Integer, nullable=True)
    # DD §6.2 rung (d): unbound routing step -> placeholder op, no
    # instruction set bound; work order flips to blocked_no_instructions.
    # ponytail: server_default=false() not the string "false" -- on SQLite a
    # server_default string is stored as raw TEXT and decoded via bool(str),
    # so the string "false" (non-empty) reads back as Python True. Postgres
    # casts the string fine either way; the portable literal is what
    # SQLite-backed tests need. (Found via tests/integration/
    # test_station_flow.py -- see app/domain/models_floor.py's superseded
    # columns for the fuller note.)
    blocked: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=false())


class PlanPdf(Base):
    """DD §8/§10: immutable, versioned PDF build-guide artifacts. Table only
    (P2-10) -- the generator lands in P2-11."""

    __tablename__ = "plan_pdfs"
    __table_args__ = (
        UniqueConstraint("work_order_id", "version", name="uq_plan_pdfs_work_order_version"),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    work_order_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("work_orders.id"), nullable=False, index=True
    )
    version: Mapped[int] = mapped_column(Integer, nullable=False)
    path: Mapped[str] = mapped_column(Text, nullable=False)
    sha256: Mapped[str] = mapped_column(Text, nullable=False)
    generated_at: Mapped[datetime] = mapped_column(nullable=False, server_default=func.now())
    # ponytail: plain text, no FK -- operators table arrives Phase 3 (same
    # deviation as instruction_sets.created_by/published_by).
    generated_by: Mapped[str | None] = mapped_column(Text, nullable=True)
