"""SQLAlchemy 2.0 models for the Floor-Execution layer (P3-02): the rest of
DD §10's "-- Execution" block that migration 0006 (P2-10) deferred --
`build_boxes`, `stations`, `operators`, `work_sessions`, `step_executions`,
`substep_executions`, measurements/attachments/materials, failures/scrap,
scans/transits, and the append-only `events`/`auth_events` audit tables.

Must match `migrations/versions/0007_floor.py` exactly -- hand-written, not
autogenerated, kept in sync by hand (see
tests/unit/test_models_match_migration.py).

Governing contract: docs/state-machine.md (P3-01) resolves per-unit
operation state WITHOUT a new table -- `step_executions`/`substep_executions`
are keyed `(plan_operation_id, unit_id)` and `units.current_plan_op_id`
(migration 0006) is the unit's position pointer. See that doc's §2.

DEVIATIONS from the DD §10 literal schema sketch (see migration 0007's
docstring for the full rationale on each):
  - `stations.work_center_code` (text) replaces the DD's `work_center_id fk`
    -- joins to `jb2_work_centers.code` as a soft mirror-refresh-safe key,
    not an enforced FK (mirror rows can be dropped/recreated by sync).
  - `box_assignments.assigned_by` / operators' role FKs that would point at
    a not-yet-existing table at DD-sketch time are all fine now since
    `operators` is created in this same migration, but `plan_operations
    .station_hint` (omitted since 0006) is intentionally NOT retrofitted
    here -- out of this task's scope, left for whoever revisits 0006.
  - `work_sessions.close_reason` and the `superseded` bool columns on
    step/substep executions are additions beyond DD's literal column list,
    required by state-machine.md §5/§6 (rework supersedes rather than
    deletes; auto-closed sessions need a reason before O6 lead confirm).
  - `request_dedup` is not in the DD §10 sketch at all -- it is
    state-machine.md §7's idempotency store, added here per that contract.
"""
from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    JSON,
    BigInteger,
    Boolean,
    CheckConstraint,
    ForeignKey,
    Integer,
    Numeric,
    Text,
    UniqueConstraint,
    Uuid,
    false,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func

from app.domain.models_jb2 import Base, _uuid_pk

# ponytail: same portable JSON type as models_jb2.py/models_library.py/
# models_execution.py.
_JSONB = JSON().with_variant(JSONB(), "postgresql")

WORK_SESSION_KINDS = ("first_pass", "rework", "setup")
WORK_SESSION_CLOSE_REASONS = ("finished", "clocked_out", "auto_closed")
PAUSE_REASON_CODES = (
    "waiting_material",
    "machine_down",
    "break",
    "pulled_to_other_job",
    "other",
)
SUBSTEP_STATUSES = ("pending", "in_progress", "done", "failed", "skipped")
ATTACHMENT_KINDS = ("photo", "file")
FAILURE_DISPOSITIONS = ("rework_in_place", "rework_to_op", "scrap", "use_as_is")
SCAN_RESULTS = ("accepted", "wrong_station", "unknown_box", "unbound_box", "rejected")
AUTH_EVENT_KINDS = ("login", "logout", "badge_fail", "pin_fail", "override")
OPERATOR_ROLES = ("operator", "lead", "quality", "librarian", "admin")


class Operator(Base):
    """DD §10/§14: floor operator identity -- badge QR or PIN login, roles
    array drives the override matrix (state-machine.md §4)."""

    __tablename__ = "operators"

    id: Mapped[uuid.UUID] = _uuid_pk()
    jb2_employee_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("jb2_employees.id"), nullable=True, index=True
    )
    display_name: Mapped[str] = mapped_column(Text, nullable=False)
    badge_qr: Mapped[str | None] = mapped_column(Text, nullable=True, unique=True)
    pin_hash: Mapped[str | None] = mapped_column(Text, nullable=True)
    # ponytail: portable JSON list of role strings rather than Postgres
    # text[] -- DD literal says text[], but JSON keeps this queryable/
    # constructible the same way on SQLite for unit tests (same tradeoff
    # models_library.py/models_execution.py already make for jsonb columns).
    roles: Mapped[list] = mapped_column(_JSONB, nullable=False, server_default="[]")
    active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="true")


class Station(Base):
    """DD §10: a floor kiosk/work-center location. `work_center_code` is a
    soft join key to `jb2_work_centers.code`, not an FK -- see module
    docstring / migration 0007 docstring for why it can't be enforced."""

    __tablename__ = "stations"

    id: Mapped[uuid.UUID] = _uuid_pk()
    name: Mapped[str] = mapped_column(Text, nullable=False)
    work_center_code: Mapped[str | None] = mapped_column(Text, nullable=True, index=True)
    location: Mapped[str | None] = mapped_column(Text, nullable=True)
    kiosk_token: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="true")
    last_seen_at: Mapped[datetime | None] = mapped_column(nullable=True)


class BuildBox(Base):
    """DD §10/§6.1.5/§17.6: the physical traveler box bound to a unit while
    it moves the floor."""

    __tablename__ = "build_boxes"

    id: Mapped[uuid.UUID] = _uuid_pk()
    qr_payload: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    label: Mapped[str | None] = mapped_column(Text, nullable=True)
    active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="true")
    current_unit_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("units.id"), nullable=True, index=True
    )
    current_station_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("stations.id"), nullable=True, index=True
    )
    last_scan_at: Mapped[datetime | None] = mapped_column(nullable=True)


class BoxAssignment(Base):
    """DD §10/§17.6: box<->unit binding history, append-only (reassignment
    closes the old row via `released_at` rather than deleting it)."""

    __tablename__ = "box_assignments"

    id: Mapped[uuid.UUID] = _uuid_pk()
    box_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("build_boxes.id"), nullable=False, index=True
    )
    unit_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("units.id"), nullable=False, index=True
    )
    # ponytail: text, not an operator FK -- DD literal says "assigned_by fk"
    # but the task brief for this table specifies plain text; kit-up may be
    # done by role names/config rather than always a resolvable operator
    # row (e.g. system-assigned). Kept as text per brief; revisit if P3-11
    # needs the FK.
    assigned_by: Mapped[str | None] = mapped_column(Text, nullable=True)
    assigned_at: Mapped[datetime] = mapped_column(nullable=False, server_default=func.now())
    released_at: Mapped[datetime | None] = mapped_column(nullable=True)


class WorkSession(Base):
    """DD §10/§6.4/§6.7, state-machine.md §6: one operator's timed
    attendance on (unit, plan_operation) at a station."""

    __tablename__ = "work_sessions"
    __table_args__ = (
        CheckConstraint(
            "kind in ('first_pass','rework','setup')", name="ck_work_sessions_kind"
        ),
        CheckConstraint(
            "close_reason is null or close_reason in "
            "('finished','clocked_out','auto_closed')",
            name="ck_work_sessions_close_reason",
        ),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    unit_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("units.id"), nullable=False, index=True
    )
    plan_operation_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("plan_operations.id"), nullable=False, index=True
    )
    operator_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("operators.id"), nullable=False, index=True
    )
    station_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("stations.id"), nullable=False, index=True
    )
    started_at: Mapped[datetime] = mapped_column(nullable=False, server_default=func.now())
    ended_at: Mapped[datetime | None] = mapped_column(nullable=True)
    kind: Mapped[str] = mapped_column(Text, nullable=False)
    # DD §10 literal list has no close_reason; state-machine.md §5/§6/§17.8
    # requires distinguishing finished/clocked_out/auto_closed (drives the
    # O6 lead-confirm gate before an auto_closed session's time posts to
    # JB2). Added per that contract -- see module docstring.
    close_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    # ponytail: server_default=false() (a real SQL boolean literal), not the
    # string "false" -- on SQLite, a server_default string is stored as TEXT
    # and read back via bool(str), so "false" (a non-empty string) decodes
    # as Python True. Postgres casts the string fine either way, but the
    # portable literal is what SQLite-backed tests need to see the correct
    # default. See tests/integration/test_station_flow.py's debugging note.
    lead_confirmed: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=false())
    jb2_outbox_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("jb2_outbox.id"), nullable=True
    )


class SessionPause(Base):
    """DD §10/§6.7: pause intervals within a WorkSession; session time =
    closed_at - opened_at - sum(pauses) per state-machine.md §6."""

    __tablename__ = "session_pauses"
    __table_args__ = (
        CheckConstraint(
            "reason_code in ('waiting_material','machine_down','break',"
            "'pulled_to_other_job','other')",
            name="ck_session_pauses_reason_code",
        ),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    work_session_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("work_sessions.id"), nullable=False, index=True
    )
    reason_code: Mapped[str] = mapped_column(Text, nullable=False)
    started_at: Mapped[datetime] = mapped_column(nullable=False, server_default=func.now())
    ended_at: Mapped[datetime | None] = mapped_column(nullable=True)


class StepExecution(Base):
    """DD §10, state-machine.md §2: per-(plan_operation, unit) step
    progress -- this is where per-unit op state actually lives (§2's
    resolution: no new table, `plan_operations.status` stays the
    aggregate roll-up)."""

    __tablename__ = "step_executions"

    id: Mapped[uuid.UUID] = _uuid_pk()
    plan_operation_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("plan_operations.id"), nullable=False, index=True
    )
    unit_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("units.id"), nullable=False, index=True
    )
    step_seq: Mapped[int] = mapped_column(Integer, nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default="pending")
    started_at: Mapped[datetime | None] = mapped_column(nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(nullable=True)
    completed_by: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("operators.id"), nullable=True
    )
    # state-machine.md §5: rework resets K..N to pending but keeps prior
    # executions -- append-only history marks the old row `superseded`
    # rather than deleting/overwriting it. Not in DD's literal column list.
    # ponytail: server_default=false() -- see WorkSession.lead_confirmed's
    # comment above for why the bare string "false" is wrong on SQLite.
    superseded: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=false())


class SubstepExecution(Base):
    """DD §10/§6.4, state-machine.md §5: per-substep completion record."""

    __tablename__ = "substep_executions"
    __table_args__ = (
        CheckConstraint(
            "status in ('pending','in_progress','done','failed','skipped')",
            name="ck_substep_executions_status",
        ),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    step_execution_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("step_executions.id"), nullable=False, index=True
    )
    substep_seq: Mapped[int] = mapped_column(Integer, nullable=False)
    type: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default="pending")
    operator_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("operators.id"), nullable=True
    )
    started_at: Mapped[datetime | None] = mapped_column(nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(nullable=True)
    value_numeric: Mapped[float | None] = mapped_column(Numeric, nullable=True)
    value_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    pass_: Mapped[bool | None] = mapped_column("pass", Boolean, nullable=True)
    out_of_tolerance: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    disposition: Mapped[str | None] = mapped_column(Text, nullable=True)
    disposition_by: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("operators.id"), nullable=True
    )
    skip_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    skip_authorized_by: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("operators.id"), nullable=True
    )
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    # ponytail: server_default=false() -- see WorkSession.lead_confirmed's
    # comment above for why the bare string "false" is wrong on SQLite.
    superseded: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=false())


class Measurement(Base):
    """DD §9.4/§10: one recorded measurement against a substep's spec."""

    __tablename__ = "measurements"

    id: Mapped[uuid.UUID] = _uuid_pk()
    substep_execution_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("substep_executions.id"), nullable=False, index=True
    )
    name: Mapped[str] = mapped_column(Text, nullable=False)
    unit: Mapped[str | None] = mapped_column(Text, nullable=True)
    value: Mapped[float] = mapped_column(Numeric, nullable=False)
    nominal: Mapped[float | None] = mapped_column(Numeric, nullable=True)
    tol_plus: Mapped[float | None] = mapped_column(Numeric, nullable=True)
    tol_minus: Mapped[float | None] = mapped_column(Numeric, nullable=True)
    in_tolerance: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    gauge_id: Mapped[str | None] = mapped_column(Text, nullable=True)
    recorded_by: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("operators.id"), nullable=False
    )
    recorded_at: Mapped[datetime] = mapped_column(nullable=False, server_default=func.now())


class Attachment(Base):
    """DD §9.5/§10: photo/file artifact linked polymorphically to whatever
    row produced it (`entity_kind`/`entity_id`, no FK -- entity_kind
    selects the target table at the application layer)."""

    __tablename__ = "attachments"
    __table_args__ = (
        CheckConstraint("kind in ('photo','file')", name="ck_attachments_kind"),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    entity_kind: Mapped[str] = mapped_column(Text, nullable=False)
    entity_id: Mapped[uuid.UUID] = mapped_column(Uuid(as_uuid=True), nullable=False, index=True)
    kind: Mapped[str] = mapped_column(Text, nullable=False)
    path: Mapped[str] = mapped_column(Text, nullable=False)
    sha256: Mapped[str] = mapped_column(Text, nullable=False)
    uploaded_by: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("operators.id"), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(nullable=False, server_default=func.now())


class MaterialRecord(Base):
    """DD §9.5/§10: material consumption against a plan operation."""

    __tablename__ = "material_records"

    id: Mapped[uuid.UUID] = _uuid_pk()
    substep_execution_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("substep_executions.id"), nullable=True, index=True
    )
    unit_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("units.id"), nullable=False, index=True
    )
    plan_operation_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("plan_operations.id"), nullable=False, index=True
    )
    part_number: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    lot: Mapped[str | None] = mapped_column(Text, nullable=True)
    qty_planned: Mapped[float | None] = mapped_column(Numeric, nullable=True)
    qty_used: Mapped[float] = mapped_column(Numeric, nullable=False)
    qty_scrapped: Mapped[float] = mapped_column(Numeric, nullable=False, server_default="0")
    unit: Mapped[str | None] = mapped_column(Text, nullable=True)
    substitution_for: Mapped[str | None] = mapped_column(Text, nullable=True)
    authorized_by: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("operators.id"), nullable=True
    )
    recorded_at: Mapped[datetime] = mapped_column(nullable=False, server_default=func.now())


class Failure(Base):
    """DD §6.5/§10: a recorded failure and its disposition."""

    __tablename__ = "failures"
    __table_args__ = (
        CheckConstraint(
            "disposition in ('rework_in_place','rework_to_op','scrap','use_as_is')",
            name="ck_failures_disposition",
        ),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    unit_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("units.id"), nullable=False, index=True
    )
    plan_operation_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("plan_operations.id"), nullable=False, index=True
    )
    substep_execution_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("substep_executions.id"), nullable=True, index=True
    )
    failure_code_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("failure_codes.id"), nullable=False, index=True
    )
    narrative: Mapped[str | None] = mapped_column(Text, nullable=True)
    detected_by: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("operators.id"), nullable=False
    )
    detected_at: Mapped[datetime] = mapped_column(nullable=False, server_default=func.now())
    introduced_at_op: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("plan_operations.id"), nullable=True
    )
    disposition: Mapped[str] = mapped_column(Text, nullable=False)
    rework_to_op: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("plan_operations.id"), nullable=True
    )
    authorized_by: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("operators.id"), nullable=True
    )


class ScrapEvent(Base):
    """DD §6.5/§10/§17: scrap disposition and optional remake link."""

    __tablename__ = "scrap_events"

    id: Mapped[uuid.UUID] = _uuid_pk()
    unit_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("units.id"), nullable=False, index=True
    )
    failure_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("failures.id"), nullable=False, index=True
    )
    cause_code: Mapped[str | None] = mapped_column(Text, nullable=True)
    narrative: Mapped[str | None] = mapped_column(Text, nullable=True)
    material_value_est: Mapped[float | None] = mapped_column(Numeric, nullable=True)
    authorized_by: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("operators.id"), nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(nullable=False, server_default=func.now())
    replacement_unit_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("units.id"), nullable=True
    )


class Scan(Base):
    """DD §6.3/§10, state-machine.md §3: every POST /scan resolution,
    accepted or not."""

    __tablename__ = "scans"
    __table_args__ = (
        CheckConstraint(
            "result in ('accepted','wrong_station','unknown_box','unbound_box',"
            "'rejected')",
            name="ck_scans_result",
        ),
        # DD §10 "Key indexes": scans(scanned_at)
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    box_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("build_boxes.id"), nullable=True, index=True
    )
    station_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("stations.id"), nullable=False, index=True
    )
    operator_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("operators.id"), nullable=True, index=True
    )
    scanned_at: Mapped[datetime] = mapped_column(nullable=False, server_default=func.now())
    raw_payload: Mapped[str] = mapped_column(Text, nullable=False)
    result: Mapped[str] = mapped_column(Text, nullable=False)
    override_by: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("operators.id"), nullable=True
    )
    work_session_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("work_sessions.id"), nullable=True
    )


class Transit(Base):
    """DD §6.7/8/§10: a unit's in-transit hop between two stations."""

    __tablename__ = "transits"

    id: Mapped[uuid.UUID] = _uuid_pk()
    unit_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("units.id"), nullable=False, index=True
    )
    from_station_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("stations.id"), nullable=True
    )
    to_station_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("stations.id"), nullable=True
    )
    departed_at: Mapped[datetime] = mapped_column(nullable=False, server_default=func.now())
    arrived_at: Mapped[datetime | None] = mapped_column(nullable=True)
    seconds: Mapped[int | None] = mapped_column(Integer, nullable=True)


class Event(Base):
    """DD §9.10/§10: append-only audit trail -- every state transition
    writes exactly one row here (state-machine.md §9/§10g). No UPDATE/DELETE
    path in the app layer; DB-level enforcement (REVOKE UPDATE/DELETE) is a
    prod runbook item, not yet wired -- see docs/runbooks/deploy.md."""

    __tablename__ = "events"

    # DD literal: "id bigserial". Postgres gets a real bigserial (Identity);
    # SQLite (unit tests) falls back to its native autoincrement rowid via
    # plain Integer/BigInteger with autoincrement=True -- same portable-
    # dialect pattern used elsewhere in this codebase for PG-only features.
    id: Mapped[int] = mapped_column(
        BigInteger().with_variant(Integer(), "sqlite"),  # sqlite rowid-aliases INTEGER only
        primary_key=True,
        autoincrement=True,
    )
    at: Mapped[datetime] = mapped_column(nullable=False, server_default=func.now())
    actor_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("operators.id"), nullable=True, index=True
    )
    station_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("stations.id"), nullable=True
    )
    entity_kind: Mapped[str] = mapped_column(Text, nullable=False)
    entity_id: Mapped[uuid.UUID | None] = mapped_column(Uuid(as_uuid=True), nullable=True)
    verb: Mapped[str] = mapped_column(Text, nullable=False)
    before: Mapped[dict | None] = mapped_column(_JSONB, nullable=True)
    after: Mapped[dict | None] = mapped_column(_JSONB, nullable=True)


class AuthEvent(Base):
    """DD §10/§14: badge/PIN auth outcomes, including overrides (this task's
    brief extends the DD's literal enum with 'override' for the second-badge
    override matrix, state-machine.md §4)."""

    __tablename__ = "auth_events"
    __table_args__ = (
        CheckConstraint(
            "kind in ('login','logout','badge_fail','pin_fail','override')",
            name="ck_auth_events_kind",
        ),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    operator_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("operators.id"), nullable=True, index=True
    )
    station_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), ForeignKey("stations.id"), nullable=True
    )
    kind: Mapped[str] = mapped_column(Text, nullable=False)
    at: Mapped[datetime] = mapped_column(nullable=False, server_default=func.now())


class RequestDedup(Base):
    """state-machine.md §7: idempotency store for floor POSTs -- a client
    `request_id` replay returns the original response rather than
    re-executing the transition. Not in DD §10's literal table list; added
    per the P3-01 contract (small, justified deviation -- see task brief)."""

    __tablename__ = "request_dedup"
    __table_args__ = (
        UniqueConstraint("request_id", name="uq_request_dedup_request_id"),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    request_id: Mapped[str] = mapped_column(Text, nullable=False)
    endpoint: Mapped[str] = mapped_column(Text, nullable=False)
    response: Mapped[dict | None] = mapped_column(_JSONB, nullable=True)
    created_at: Mapped[datetime] = mapped_column(nullable=False, server_default=func.now())
