"""SQLAlchemy 2.0 models for the JB2 mirror layer (DD §10 "-- JB2 mirrors" block).

Must match `migrations/versions/0001_jb2_mirrors.py` exactly — that migration
is hand-written, not autogenerated from these models, so the two are kept in
sync by hand (see tests/unit/test_models_match_migration.py).

DEFERRED-VERIFY: run against live Postgres 16 when available (plan §9).

`JB2Outbox.work_order_id` is a plain nullable uuid column with **no FK** —
`work_orders` doesn't exist until Phase 2 (migration 0003 adds the FK).
"""
from __future__ import annotations

import uuid
from datetime import date, datetime
from decimal import Decimal

from sqlalchemy import Boolean, CheckConstraint, Date, ForeignKey, Integer, Numeric, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.sql import func


class Base(DeclarativeBase):
    pass


def _uuid_pk() -> Mapped[uuid.UUID]:
    return mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )


class MirrorMixin:
    """Common columns for every jb2_* mirror row (DD §4.2)."""

    payload: Mapped[dict] = mapped_column(JSONB, nullable=False)
    content_hash: Mapped[str] = mapped_column(Text, nullable=False)
    jb2_last_modified: Mapped[datetime | None] = mapped_column(nullable=True)
    synced_at: Mapped[datetime] = mapped_column(nullable=False)
    created_at: Mapped[datetime] = mapped_column(nullable=False, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(nullable=False, server_default=func.now())


class JB2Order(MirrorMixin, Base):
    __tablename__ = "jb2_orders"

    id: Mapped[uuid.UUID] = _uuid_pk()
    jb2_id: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    order_number: Mapped[str | None] = mapped_column(Text, nullable=True)
    customer: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str | None] = mapped_column(Text, nullable=True)
    due_date: Mapped[date | None] = mapped_column(Date, nullable=True)


class JB2OrderLineItem(MirrorMixin, Base):
    __tablename__ = "jb2_order_line_items"

    id: Mapped[uuid.UUID] = _uuid_pk()
    jb2_id: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    jb2_order_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("jb2_orders.id"), nullable=True, index=True
    )
    part_number: Mapped[str | None] = mapped_column(Text, nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    qty: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    due_date: Mapped[date | None] = mapped_column(Date, nullable=True)


class JB2OrderRouting(MirrorMixin, Base):
    __tablename__ = "jb2_order_routings"

    id: Mapped[uuid.UUID] = _uuid_pk()
    jb2_id: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    jb2_line_item_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("jb2_order_line_items.id"), nullable=True, index=True
    )
    seq: Mapped[int | None] = mapped_column(Integer, nullable=True)
    operation_code: Mapped[str | None] = mapped_column(Text, nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    work_center_code: Mapped[str | None] = mapped_column(Text, nullable=True)
    est_setup_hrs: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    est_run_hrs: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)


class JB2OrderMaterial(MirrorMixin, Base):
    __tablename__ = "jb2_order_materials"

    id: Mapped[uuid.UUID] = _uuid_pk()
    jb2_id: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    jb2_line_item_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("jb2_order_line_items.id"), nullable=True, index=True
    )
    routing_seq: Mapped[int | None] = mapped_column(Integer, nullable=True)
    part_number: Mapped[str | None] = mapped_column(Text, nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    qty_planned: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    unit: Mapped[str | None] = mapped_column(Text, nullable=True)
    unit_cost: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)


class JB2Part(MirrorMixin, Base):
    __tablename__ = "jb2_parts"

    id: Mapped[uuid.UUID] = _uuid_pk()
    jb2_id: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    part_number: Mapped[str | None] = mapped_column(Text, nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    revision: Mapped[str | None] = mapped_column(Text, nullable=True)


class JB2WorkCenter(MirrorMixin, Base):
    __tablename__ = "jb2_work_centers"

    id: Mapped[uuid.UUID] = _uuid_pk()
    jb2_id: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    code: Mapped[str | None] = mapped_column(Text, nullable=True)
    name: Mapped[str | None] = mapped_column(Text, nullable=True)


class JB2Employee(MirrorMixin, Base):
    __tablename__ = "jb2_employees"

    id: Mapped[uuid.UUID] = _uuid_pk()
    jb2_id: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    employee_code: Mapped[str | None] = mapped_column(Text, nullable=True)
    name: Mapped[str | None] = mapped_column(Text, nullable=True)
    active: Mapped[bool | None] = mapped_column(Boolean, nullable=True)


class JB2OperationCode(MirrorMixin, Base):
    __tablename__ = "jb2_operation_codes"

    id: Mapped[uuid.UUID] = _uuid_pk()
    code: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    work_center_code: Mapped[str | None] = mapped_column(Text, nullable=True)


class JB2ReasonCode(MirrorMixin, Base):
    __tablename__ = "jb2_reason_codes"

    id: Mapped[uuid.UUID] = _uuid_pk()
    reason_number: Mapped[int] = mapped_column(Integer, nullable=False, unique=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)


class JB2Document(MirrorMixin, Base):
    __tablename__ = "jb2_documents"

    id: Mapped[uuid.UUID] = _uuid_pk()
    jb2_id: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    document_number: Mapped[str | None] = mapped_column(Text, nullable=True)
    revision: Mapped[str | None] = mapped_column(Text, nullable=True)
    linked_part_number: Mapped[str | None] = mapped_column(Text, nullable=True)


class SyncRun(Base):
    __tablename__ = "sync_runs"

    id: Mapped[uuid.UUID] = _uuid_pk()
    resource: Mapped[str] = mapped_column(Text, nullable=False)
    started_at: Mapped[datetime] = mapped_column(nullable=False)
    finished_at: Mapped[datetime | None] = mapped_column(nullable=True)
    fetched: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    changed: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    error: Mapped[str | None] = mapped_column(Text, nullable=True)


class JB2Outbox(Base):
    __tablename__ = "jb2_outbox"
    __table_args__ = (
        CheckConstraint(
            "status in ('pending','sent','confirmed','failed')", name="ck_jb2_outbox_status"
        ),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    kind: Mapped[str] = mapped_column(Text, nullable=False)
    payload: Mapped[dict] = mapped_column(JSONB, nullable=False)
    idempotency_key: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default="pending")
    attempts: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    last_error: Mapped[str | None] = mapped_column(Text, nullable=True)
    # ponytail: plain uuid column, no FK. work_orders arrives in Phase 2;
    # migration 0003 adds `ForeignKey("work_orders.id")` once it exists.
    work_order_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        nullable=True,
        index=True,
        comment="Future FK to work_orders.id — added in migration 0003 (Phase 2).",
    )
    created_at: Mapped[datetime] = mapped_column(nullable=False, server_default=func.now())
    sent_at: Mapped[datetime | None] = mapped_column(nullable=True)
    confirmed_at: Mapped[datetime | None] = mapped_column(nullable=True)


class MappingException(Base):
    __tablename__ = "mapping_exceptions"

    id: Mapped[uuid.UUID] = _uuid_pk()
    kind: Mapped[str] = mapped_column(Text, nullable=False)
    value: Mapped[str] = mapped_column(Text, nullable=False)
    context: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    resolved: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="false")
    created_at: Mapped[datetime] = mapped_column(nullable=False, server_default=func.now())
